#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Consumable_ChargeInjector

#include "Basic.hpp"

#include "BP_Consumable_ChargeInjector_classes.hpp"
#include "BP_Consumable_ChargeInjector_parameters.hpp"


namespace SDK
{

// Function BP_Consumable_ChargeInjector.BP_Consumable_ChargeInjector_C.EndEquipmentFOV
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Consumable_ChargeInjector_C::EndEquipmentFOV()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Consumable_ChargeInjector_C", "EndEquipmentFOV");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Consumable_ChargeInjector.BP_Consumable_ChargeInjector_C.EndEquipmentHUD
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Consumable_ChargeInjector_C::EndEquipmentHUD()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Consumable_ChargeInjector_C", "EndEquipmentHUD");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Consumable_ChargeInjector.BP_Consumable_ChargeInjector_C.EquipmentCleanUp
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Consumable_ChargeInjector_C::EquipmentCleanUp()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Consumable_ChargeInjector_C", "EquipmentCleanUp");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Consumable_ChargeInjector.BP_Consumable_ChargeInjector_C.ExecuteUbergraph_BP_Consumable_ChargeInjector
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Consumable_ChargeInjector_C::ExecuteUbergraph_BP_Consumable_ChargeInjector(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Consumable_ChargeInjector_C", "ExecuteUbergraph_BP_Consumable_ChargeInjector");

	Params::BP_Consumable_ChargeInjector_C_ExecuteUbergraph_BP_Consumable_ChargeInjector Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Consumable_ChargeInjector.BP_Consumable_ChargeInjector_C.StartConsumeAnimation
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Consumable_ChargeInjector_C::StartConsumeAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Consumable_ChargeInjector_C", "StartConsumeAnimation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Consumable_ChargeInjector.BP_Consumable_ChargeInjector_C.StartEquipmentFOV
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Consumable_ChargeInjector_C::StartEquipmentFOV()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Consumable_ChargeInjector_C", "StartEquipmentFOV");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Consumable_ChargeInjector.BP_Consumable_ChargeInjector_C.StartEquipmentHUD
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Consumable_ChargeInjector_C::StartEquipmentHUD()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Consumable_ChargeInjector_C", "StartEquipmentHUD");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Consumable_ChargeInjector.BP_Consumable_ChargeInjector_C.Timeline__FinishedFunc
// (BlueprintEvent)

void ABP_Consumable_ChargeInjector_C::Timeline__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Consumable_ChargeInjector_C", "Timeline__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Consumable_ChargeInjector.BP_Consumable_ChargeInjector_C.Timeline__UpdateFunc
// (BlueprintEvent)

void ABP_Consumable_ChargeInjector_C::Timeline__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Consumable_ChargeInjector_C", "Timeline__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}

}

