#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Dialog_Cheat_Maps

#include "Basic.hpp"

#include "Voyage_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BP_Dialog_Cheat_Maps.BP_Dialog_Cheat_Maps_C
// 0x00C8 (0x0888 - 0x07C0)
class UBP_Dialog_Cheat_Maps_C final : public UVoyageBaseDialogWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x07C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBP_FocusableButton_C*                  WeaponsPlayground_Btn;                             // 0x07C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_FocusableButton_C*                  Trash_Btn;                                         // 0x07D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_FocusableButton_C*                  QuestFlow_Btn;                                     // 0x07D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_FocusableButton_C*                  MovementShowcase_Btn;                              // 0x07E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_FocusableButton_C*                  ModuleShowcase_Btn;                                // 0x07E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_FocusableButton_C*                  LogicTests_Btn;                                    // 0x07F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_FocusableButton_C*                  HumanGrow_Btn;                                     // 0x07F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_FocusableButton_C*                  FlyThrough_Btn;                                    // 0x0800(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_FocusableButton_C*                  CraftingShowcase_Btn;                              // 0x0808(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_FocusableButton_C*                  ConsumptionTests_Btn;                              // 0x0810(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_FocusableButton_C*                  CancelBtn;                                         // 0x0818(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_FocusableButton_C*                  Boat_Btn;                                          // 0x0820(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_FocusableButton_C*                  Achiements_Btn;                                    // 0x0828(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       NewAnimation;                                      // 0x0830(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	TMap<int32, class FName>                      Maps;                                              // 0x0838(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void Change_map(class FName Level_name);
	void ExecuteUbergraph_BP_Dialog_Cheat_Maps(int32 EntryPoint);
	void OnConfirm(const struct FVoyageDialogResult& DialogResult);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Dialog_Cheat_Maps_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Dialog_Cheat_Maps_C")
	}
	static class UBP_Dialog_Cheat_Maps_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Dialog_Cheat_Maps_C>();
	}
};
DUMPER7_ASSERTS_UBP_Dialog_Cheat_Maps_C;

}

