#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Deco_Int_Hanging_Wires

#include "Basic.hpp"

#include "BP_P_LinearStruct_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Deco_Int_Hanging_Wires.BP_Deco_Int_Hanging_Wires_C
// 0x0000 (0x04B8 - 0x04B8)
class ABP_Deco_Int_Hanging_Wires_C final : public ABP_P_LinearStruct_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Deco_Int_Hanging_Wires_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Deco_Int_Hanging_Wires_C")
	}
	static class ABP_Deco_Int_Hanging_Wires_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Deco_Int_Hanging_Wires_C>();
	}
};
DUMPER7_ASSERTS_ABP_Deco_Int_Hanging_Wires_C;

}

