#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EquipmentWidget

#include "Basic.hpp"

#include "Voyage_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BP_EquipmentWidget.BP_EquipmentWidget_C
// 0x0000 (0x0740 - 0x0740)
class UBP_EquipmentWidget_C final : public UVoyageEquipmentWidget
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_EquipmentWidget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_EquipmentWidget_C")
	}
	static class UBP_EquipmentWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_EquipmentWidget_C>();
	}
};
DUMPER7_ASSERTS_UBP_EquipmentWidget_C;

}

