#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FabricatorOverlayWidget

#include "Basic.hpp"

#include "Voyage_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BP_FabricatorOverlayWidget.BP_FabricatorOverlayWidget_C
// 0x0000 (0x06A0 - 0x06A0)
class UBP_FabricatorOverlayWidget_C final : public UVoyageScreenOverlayWidget
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_FabricatorOverlayWidget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_FabricatorOverlayWidget_C")
	}
	static class UBP_FabricatorOverlayWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_FabricatorOverlayWidget_C>();
	}
};
DUMPER7_ASSERTS_UBP_FabricatorOverlayWidget_C;

}

