#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Inventory_JetSkiBox

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_Inventory_JetSkiBox.BP_Inventory_JetSkiBox_C.ExecuteUbergraph_BP_Inventory_JetSkiBox
// 0x0004 (0x0004 - 0x0000)
struct BP_Inventory_JetSkiBox_C_ExecuteUbergraph_BP_Inventory_JetSkiBox final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Inventory_JetSkiBox_C_ExecuteUbergraph_BP_Inventory_JetSkiBox;

}

