#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Module_VirtualSockets

#include "Basic.hpp"

#include "BP_Module_VirtualSockets_classes.hpp"
#include "BP_Module_VirtualSockets_parameters.hpp"


namespace SDK
{

// Function BP_Module_VirtualSockets.BP_Module_VirtualSockets_C.ExecuteUbergraph_BP_Module_VirtualSockets
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Module_VirtualSockets_C::ExecuteUbergraph_BP_Module_VirtualSockets(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Module_VirtualSockets_C", "ExecuteUbergraph_BP_Module_VirtualSockets");

	Params::BP_Module_VirtualSockets_C_ExecuteUbergraph_BP_Module_VirtualSockets Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Module_VirtualSockets.BP_Module_VirtualSockets_C.HideSocketView
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UVoyageModuleSocketViewComponent* SocketView                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void ABP_Module_VirtualSockets_C::HideSocketView(class UVoyageModuleSocketViewComponent* SocketView)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Module_VirtualSockets_C", "HideSocketView");

	Params::BP_Module_VirtualSockets_C_HideSocketView Parms{};

	Parms.SocketView = SocketView;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Module_VirtualSockets.BP_Module_VirtualSockets_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Module_VirtualSockets_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Module_VirtualSockets_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Module_VirtualSockets.BP_Module_VirtualSockets_C.SetupSocket
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UVoyageModuleSocketViewComponent* SocketView                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void ABP_Module_VirtualSockets_C::SetupSocket(class UVoyageModuleSocketViewComponent* SocketView)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Module_VirtualSockets_C", "SetupSocket");

	Params::BP_Module_VirtualSockets_C_SetupSocket Parms{};

	Parms.SocketView = SocketView;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Module_VirtualSockets.BP_Module_VirtualSockets_C.UpdateMaterialFromResourceType
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Module_VirtualSockets_C::UpdateMaterialFromResourceType()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Module_VirtualSockets_C", "UpdateMaterialFromResourceType");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Module_VirtualSockets.BP_Module_VirtualSockets_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_Module_VirtualSockets_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Module_VirtualSockets_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

