#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_NormalDoor_Double_Boat

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_NormalDoor_Double_Boat.BP_NormalDoor_Double_Boat_C.ExecuteUbergraph_BP_NormalDoor_Double_Boat
// 0x0004 (0x0004 - 0x0000)
struct BP_NormalDoor_Double_Boat_C_ExecuteUbergraph_BP_NormalDoor_Double_Boat final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_NormalDoor_Double_Boat_C_ExecuteUbergraph_BP_NormalDoor_Double_Boat;

}

