#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Rocket_Functional

#include "Basic.hpp"

#include "BP_Rocket_Functional_classes.hpp"
#include "BP_Rocket_Functional_parameters.hpp"


namespace SDK
{

// Function BP_Rocket_Functional.BP_Rocket_Functional_C.BndEvt__BP_Rocket_Functional_SM_Top_Door_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              HitComponent                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   NormalImpulse                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FHitResult&                Hit                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ABP_Rocket_Functional_C::BndEvt__BP_Rocket_Functional_SM_Top_Door_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature(class UPrimitiveComponent* HitComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, const struct FVector& NormalImpulse, const struct FHitResult& Hit)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "BndEvt__BP_Rocket_Functional_SM_Top_Door_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature");

	Params::BP_Rocket_Functional_C_BndEvt__BP_Rocket_Functional_SM_Top_Door_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature Parms{};

	Parms.HitComponent = HitComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.NormalImpulse = std::move(NormalImpulse);
	Parms.Hit = std::move(Hit);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.CanBeInteractedBy
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           InInteractor                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// int32                                   PartId                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   InteractIndex                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EInteractionConditionType               ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

EInteractionConditionType ABP_Rocket_Functional_C::CanBeInteractedBy(class AActor* InInteractor, int32 PartId, int32 InteractIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "CanBeInteractedBy");

	Params::BP_Rocket_Functional_C_CanBeInteractedBy Parms{};

	Parms.InInteractor = InInteractor;
	Parms.PartId = PartId;
	Parms.InteractIndex = InteractIndex;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.CanInteractFuelHatch
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   bCanClose                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::CanInteractFuelHatch(int32 Index_0, bool* bCanClose)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "CanInteractFuelHatch");

	Params::BP_Rocket_Functional_C_CanInteractFuelHatch Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);

	if (bCanClose != nullptr)
		*bCanClose = Parms.bCanClose;
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.DoLaunchPlayback
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_Rocket_Functional_C::DoLaunchPlayback()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "DoLaunchPlayback");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.ExecuteUbergraph_BP_Rocket_Functional
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::ExecuteUbergraph_BP_Rocket_Functional(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "ExecuteUbergraph_BP_Rocket_Functional");

	Params::BP_Rocket_Functional_C_ExecuteUbergraph_BP_Rocket_Functional Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.GetActorsInsideRocket
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class AActor*>*                  OutActors                                              (Parm, OutParm)

void ABP_Rocket_Functional_C::GetActorsInsideRocket(TArray<class AActor*>* OutActors)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "GetActorsInsideRocket");

	Params::BP_Rocket_Functional_C_GetActorsInsideRocket Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (OutActors != nullptr)
		*OutActors = std::move(Parms.OutActors);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.GetDoorInteractText
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText*                            Text                                                   (Parm, OutParm)

void ABP_Rocket_Functional_C::GetDoorInteractText(class FText* Text)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "GetDoorInteractText");

	Params::BP_Rocket_Functional_C_GetDoorInteractText Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Text != nullptr)
		*Text = std::move(Parms.Text);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.GetFuelHatchInteractText
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText*                            Text                                                   (Parm, OutParm)

void ABP_Rocket_Functional_C::GetFuelHatchInteractText(int32 Index_0, class FText* Text)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "GetFuelHatchInteractText");

	Params::BP_Rocket_Functional_C_GetFuelHatchInteractText Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);

	if (Text != nullptr)
		*Text = std::move(Parms.Text);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.GetFuelProgress
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double*                                 Progress                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::GetFuelProgress(int32 Index_0, double* Progress)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "GetFuelProgress");

	Params::BP_Rocket_Functional_C_GetFuelProgress Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);

	if (Progress != nullptr)
		*Progress = Parms.Progress;
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.GetGrabText
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           InInteractor                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const class FText&                      InText                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// class FText*                            OutText                                                (Parm, OutParm)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool ABP_Rocket_Functional_C::GetGrabText(class AActor* InInteractor, const class FText& InText, class FText* OutText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "GetGrabText");

	Params::BP_Rocket_Functional_C_GetGrabText Parms{};

	Parms.InInteractor = InInteractor;
	Parms.InText = std::move(InText);

	UObject::ProcessEvent(Func, &Parms);

	if (OutText != nullptr)
		*OutText = std::move(Parms.OutText);

	return Parms.ReturnValue;
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.GetInteractCrosshair
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           InInteractor                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// int32                                   PartId                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UVoyageCrosshairWidgetData*       ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)

class UVoyageCrosshairWidgetData* ABP_Rocket_Functional_C::GetInteractCrosshair(class AActor* InInteractor, int32 PartId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "GetInteractCrosshair");

	Params::BP_Rocket_Functional_C_GetInteractCrosshair Parms{};

	Parms.InInteractor = InInteractor;
	Parms.PartId = PartId;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.GetInteractIndices
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           InInteractor                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// TArray<int32>*                          OutIndices                                             (Parm, OutParm)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool ABP_Rocket_Functional_C::GetInteractIndices(class AActor* InInteractor, TArray<int32>* OutIndices)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "GetInteractIndices");

	Params::BP_Rocket_Functional_C_GetInteractIndices Parms{};

	Parms.InInteractor = InInteractor;

	UObject::ProcessEvent(Func, &Parms);

	if (OutIndices != nullptr)
		*OutIndices = std::move(Parms.OutIndices);

	return Parms.ReturnValue;
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.GetInteractiveProvidedActions
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APawn*                            MyCharacter                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class USceneComponent*                  Component                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// TArray<struct FPlayerInputInterfaceAction>*OutActions                                             (Parm, OutParm, ContainsInstancedReference)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool ABP_Rocket_Functional_C::GetInteractiveProvidedActions(class APawn* MyCharacter, class USceneComponent* Component, TArray<struct FPlayerInputInterfaceAction>* OutActions)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "GetInteractiveProvidedActions");

	Params::BP_Rocket_Functional_C_GetInteractiveProvidedActions Parms{};

	Parms.MyCharacter = MyCharacter;
	Parms.Component = Component;

	UObject::ProcessEvent(Func, &Parms);

	if (OutActions != nullptr)
		*OutActions = std::move(Parms.OutActions);

	return Parms.ReturnValue;
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.GetInteractiveProvidedGrabActions
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APawn*                            MyCharacter                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class USceneComponent*                  Component                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// TArray<struct FPlayerInputInterfaceAction>*OutActions                                             (Parm, OutParm, ContainsInstancedReference)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool ABP_Rocket_Functional_C::GetInteractiveProvidedGrabActions(class APawn* MyCharacter, class USceneComponent* Component, TArray<struct FPlayerInputInterfaceAction>* OutActions)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "GetInteractiveProvidedGrabActions");

	Params::BP_Rocket_Functional_C_GetInteractiveProvidedGrabActions Parms{};

	Parms.MyCharacter = MyCharacter;
	Parms.Component = Component;

	UObject::ProcessEvent(Func, &Parms);

	if (OutActions != nullptr)
		*OutActions = std::move(Parms.OutActions);

	return Parms.ReturnValue;
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.GetInteractText
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           InInteractor                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// int32                                   PartId                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   InteractIndex                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText*                            OutText                                                (Parm, OutParm)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool ABP_Rocket_Functional_C::GetInteractText(class AActor* InInteractor, int32 PartId, int32 InteractIndex, class FText* OutText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "GetInteractText");

	Params::BP_Rocket_Functional_C_GetInteractText Parms{};

	Parms.InInteractor = InInteractor;
	Parms.PartId = PartId;
	Parms.InteractIndex = InteractIndex;

	UObject::ProcessEvent(Func, &Parms);

	if (OutText != nullptr)
		*OutText = std::move(Parms.OutText);

	return Parms.ReturnValue;
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.GetLazarusPod
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UVoyagePhysicalSnapSocketComponent*Target                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class AVoyageLazarusPOD**               AsVoyage_Lazarus_POD                                   (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::GetLazarusPod(class UVoyagePhysicalSnapSocketComponent* Target, class AVoyageLazarusPOD** AsVoyage_Lazarus_POD)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "GetLazarusPod");

	Params::BP_Rocket_Functional_C_GetLazarusPod Parms{};

	Parms.Target = Target;

	UObject::ProcessEvent(Func, &Parms);

	if (AsVoyage_Lazarus_POD != nullptr)
		*AsVoyage_Lazarus_POD = Parms.AsVoyage_Lazarus_POD;
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.GetNumFuelHatches
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32*                                  NumFuelHatches                                         (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::GetNumFuelHatches(int32* NumFuelHatches)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "GetNumFuelHatches");

	Params::BP_Rocket_Functional_C_GetNumFuelHatches Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (NumFuelHatches != nullptr)
		*NumFuelHatches = Parms.NumFuelHatches;
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.GetNumOccupiedPodSlots
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32*                                  NumPods                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::GetNumOccupiedPodSlots(int32* NumPods)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "GetNumOccupiedPodSlots");

	Params::BP_Rocket_Functional_C_GetNumOccupiedPodSlots Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (NumPods != nullptr)
		*NumPods = Parms.NumPods;
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.GetOwnedPersistentActorComponent
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UVoyagePersistentActorComponent*  ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UVoyagePersistentActorComponent* ABP_Rocket_Functional_C::GetOwnedPersistentActorComponent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "GetOwnedPersistentActorComponent");

	Params::BP_Rocket_Functional_C_GetOwnedPersistentActorComponent Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.GetOwningPlayerState
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class AVoyagePlayerState**              PlayerState                                            (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::GetOwningPlayerState(class AVoyagePlayerState** PlayerState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "GetOwningPlayerState");

	Params::BP_Rocket_Functional_C_GetOwningPlayerState Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (PlayerState != nullptr)
		*PlayerState = Parms.PlayerState;
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.GetPodSocketComponent
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UVoyagePhysicalSnapSocketComponent**Socket                                                 (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::GetPodSocketComponent(int32 Index_0, class UVoyagePhysicalSnapSocketComponent** Socket)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "GetPodSocketComponent");

	Params::BP_Rocket_Functional_C_GetPodSocketComponent Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);

	if (Socket != nullptr)
		*Socket = Parms.Socket;
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.GetScanText
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FVoyageScanText*                 OutText                                                (Parm, OutParm)
// class APlayerController*                InInstigator                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool ABP_Rocket_Functional_C::GetScanText(struct FVoyageScanText* OutText, class APlayerController* InInstigator)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "GetScanText");

	Params::BP_Rocket_Functional_C_GetScanText Parms{};

	Parms.InInstigator = InInstigator;

	UObject::ProcessEvent(Func, &Parms);

	if (OutText != nullptr)
		*OutText = std::move(Parms.OutText);

	return Parms.ReturnValue;
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.HasBeenLaunched
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   bLaunched                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::HasBeenLaunched(bool* bLaunched)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "HasBeenLaunched");

	Params::BP_Rocket_Functional_C_HasBeenLaunched Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (bLaunched != nullptr)
		*bLaunched = Parms.bLaunched;
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.HasPower
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool*                                   bHasPower                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::HasPower(bool* bHasPower)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "HasPower");

	Params::BP_Rocket_Functional_C_HasPower Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (bHasPower != nullptr)
		*bHasPower = Parms.bHasPower;
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.InteractAction
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APawn*                            MyCharacter                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// int32                                   PartId                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   InteractIndex                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::InteractAction(class APawn* MyCharacter, int32 PartId, int32 InteractIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "InteractAction");

	Params::BP_Rocket_Functional_C_InteractAction Parms{};

	Parms.MyCharacter = MyCharacter;
	Parms.PartId = PartId;
	Parms.InteractIndex = InteractIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.InteractActionPartial
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APawn*                            MyCharacter                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// int32                                   PartId                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   InteractIndex                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool ABP_Rocket_Functional_C::InteractActionPartial(class APawn* MyCharacter, int32 PartId, int32 InteractIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "InteractActionPartial");

	Params::BP_Rocket_Functional_C_InteractActionPartial Parms{};

	Parms.MyCharacter = MyCharacter;
	Parms.PartId = PartId;
	Parms.InteractIndex = InteractIndex;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.InteractGetInventory
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APawn*                            MyCharacter                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// int32                                   PartId                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UVoyageBaseInventoryComponent*    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UVoyageBaseInventoryComponent* ABP_Rocket_Functional_C::InteractGetInventory(class APawn* MyCharacter, int32 PartId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "InteractGetInventory");

	Params::BP_Rocket_Functional_C_InteractGetInventory Parms{};

	Parms.MyCharacter = MyCharacter;
	Parms.PartId = PartId;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.InteractWithGrab
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APawn*                            MyCharacter                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// int32                                   PartId                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EInteractWithGrabReturnValue*           OutValue                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::InteractWithGrab(class APawn* MyCharacter, int32 PartId, EInteractWithGrabReturnValue* OutValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "InteractWithGrab");

	Params::BP_Rocket_Functional_C_InteractWithGrab Parms{};

	Parms.MyCharacter = MyCharacter;
	Parms.PartId = PartId;

	UObject::ProcessEvent(Func, &Parms);

	if (OutValue != nullptr)
		*OutValue = Parms.OutValue;
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.IsAllFuelHatchesClosed
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   bAllClosed                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::IsAllFuelHatchesClosed(bool* bAllClosed)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "IsAllFuelHatchesClosed");

	Params::BP_Rocket_Functional_C_IsAllFuelHatchesClosed Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (bAllClosed != nullptr)
		*bAllClosed = Parms.bAllClosed;
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.IsDoorOpen
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   bOpen                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::IsDoorOpen(bool* bOpen)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "IsDoorOpen");

	Params::BP_Rocket_Functional_C_IsDoorOpen Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (bOpen != nullptr)
		*bOpen = Parms.bOpen;
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.IsDoorPartId
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32                                   PartId                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   bReturn                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::IsDoorPartId(int32 PartId, bool* bReturn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "IsDoorPartId");

	Params::BP_Rocket_Functional_C_IsDoorPartId Parms{};

	Parms.PartId = PartId;

	UObject::ProcessEvent(Func, &Parms);

	if (bReturn != nullptr)
		*bReturn = Parms.bReturn;
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.IsFuelHatchCableAttached
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   bCanClose                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::IsFuelHatchCableAttached(int32 Index_0, bool* bCanClose)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "IsFuelHatchCableAttached");

	Params::BP_Rocket_Functional_C_IsFuelHatchCableAttached Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);

	if (bCanClose != nullptr)
		*bCanClose = Parms.bCanClose;
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.IsFuelHatchOpen
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   bOpen                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::IsFuelHatchOpen(int32 Index_0, bool* bOpen)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "IsFuelHatchOpen");

	Params::BP_Rocket_Functional_C_IsFuelHatchOpen Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);

	if (bOpen != nullptr)
		*bOpen = Parms.bOpen;
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.IsHatchPartId
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32                                   PartId                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   bReturn                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::IsHatchPartId(int32 PartId, bool* bReturn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "IsHatchPartId");

	Params::BP_Rocket_Functional_C_IsHatchPartId Parms{};

	Parms.PartId = PartId;

	UObject::ProcessEvent(Func, &Parms);

	if (bReturn != nullptr)
		*bReturn = Parms.bReturn;
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.IsPodAttached
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   bAttached                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::IsPodAttached(int32 Index_0, bool* bAttached)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "IsPodAttached");

	Params::BP_Rocket_Functional_C_IsPodAttached Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);

	if (bAttached != nullptr)
		*bAttached = Parms.bAttached;
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.IsSnapSocketPlugged
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UVoyagePhysicalSnapSocketComponent*SnapSocket                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// bool*                                   bPlugged                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::IsSnapSocketPlugged(class UVoyagePhysicalSnapSocketComponent* SnapSocket, bool* bPlugged)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "IsSnapSocketPlugged");

	Params::BP_Rocket_Functional_C_IsSnapSocketPlugged Parms{};

	Parms.SnapSocket = SnapSocket;

	UObject::ProcessEvent(Func, &Parms);

	if (bPlugged != nullptr)
		*bPlugged = Parms.bPlugged;
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.MarkHumansLaunched
// (BlueprintCallable, BlueprintEvent)

void ABP_Rocket_Functional_C::MarkHumansLaunched()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "MarkHumansLaunched");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.MarkPodLaunched
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::MarkPodLaunched(int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "MarkPodLaunched");

	Params::BP_Rocket_Functional_C_MarkPodLaunched Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.MoneyWorth
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Rocket_Functional_C::MoneyWorth()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "MoneyWorth");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.OnAbortLaunchSequence
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UVoyageRocketStateComponent*      RocketStateComponent                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::OnAbortLaunchSequence(class UVoyageRocketStateComponent* RocketStateComponent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "OnAbortLaunchSequence");

	Params::BP_Rocket_Functional_C_OnAbortLaunchSequence Parms{};

	Parms.RocketStateComponent = RocketStateComponent;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.OnAnimationFinished
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bFinished                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::OnAnimationFinished(bool bFinished)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "OnAnimationFinished");

	Params::BP_Rocket_Functional_C_OnAnimationFinished Parms{};

	Parms.bFinished = bFinished;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.OnCountdownSecondChanged_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UVoyageRocketStateComponent*      RocketStateComponent                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   Remaining                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::OnCountdownSecondChanged_Event(class UVoyageRocketStateComponent* RocketStateComponent, int32 Remaining)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "OnCountdownSecondChanged_Event");

	Params::BP_Rocket_Functional_C_OnCountdownSecondChanged_Event Parms{};

	Parms.RocketStateComponent = RocketStateComponent;
	Parms.Remaining = Remaining;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.OnCustomDataLoad
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const TArray<uint8>&                    InData                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// int32                                   Version                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::OnCustomDataLoad(const TArray<uint8>& InData, int32 Version)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "OnCustomDataLoad");

	Params::BP_Rocket_Functional_C_OnCustomDataLoad Parms{};

	Parms.InData = std::move(InData);
	Parms.Version = Version;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.OnCustomDataSave
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<uint8>*                          OutData                                                (Parm, OutParm)

void ABP_Rocket_Functional_C::OnCustomDataSave(TArray<uint8>* OutData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "OnCustomDataSave");

	Params::BP_Rocket_Functional_C_OnCustomDataSave Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (OutData != nullptr)
		*OutData = std::move(Parms.OutData);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.OnLanded_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UVoyageRocketStateComponent*      RocketStateComponent                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::OnLanded_Event(class UVoyageRocketStateComponent* RocketStateComponent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "OnLanded_Event");

	Params::BP_Rocket_Functional_C_OnLanded_Event Parms{};

	Parms.RocketStateComponent = RocketStateComponent;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.OnLaunched
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Rocket_Functional_C::OnLaunched()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "OnLaunched");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.OnLaunched_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UVoyageRocketStateComponent*      RocketStateComponent                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::OnLaunched_Event(class UVoyageRocketStateComponent* RocketStateComponent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "OnLaunched_Event");

	Params::BP_Rocket_Functional_C_OnLaunched_Event Parms{};

	Parms.RocketStateComponent = RocketStateComponent;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.OnModuleElectricityChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UVoyageModuleComponent*           Module                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::OnModuleElectricityChanged(class UVoyageModuleComponent* Module)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "OnModuleElectricityChanged");

	Params::BP_Rocket_Functional_C_OnModuleElectricityChanged Parms{};

	Parms.Module = Module;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.OnModuleMethaneChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UVoyageModuleComponent*           Module                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::OnModuleMethaneChanged(class UVoyageModuleComponent* Module)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "OnModuleMethaneChanged");

	Params::BP_Rocket_Functional_C_OnModuleMethaneChanged Parms{};

	Parms.Module = Module;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.OnModuleOxygenChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UVoyageModuleComponent*           Module                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::OnModuleOxygenChanged(class UVoyageModuleComponent* Module)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "OnModuleOxygenChanged");

	Params::BP_Rocket_Functional_C_OnModuleOxygenChanged Parms{};

	Parms.Module = Module;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.OnModuleValueChanged
// (BlueprintCallable, BlueprintEvent)

void ABP_Rocket_Functional_C::OnModuleValueChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "OnModuleValueChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.OnPersistentActorPostLoad
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Version                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::OnPersistentActorPostLoad(int32 Version)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "OnPersistentActorPostLoad");

	Params::BP_Rocket_Functional_C_OnPersistentActorPostLoad Parms{};

	Parms.Version = Version;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.OnPersistentActorPrepareSave
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_Rocket_Functional_C::OnPersistentActorPrepareSave()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "OnPersistentActorPrepareSave");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.OnPersistentActorPreSave
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_Rocket_Functional_C::OnPersistentActorPreSave()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "OnPersistentActorPreSave");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.OnPersistentSubsystemPostLoad
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Version                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::OnPersistentSubsystemPostLoad(int32 Version)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "OnPersistentSubsystemPostLoad");

	Params::BP_Rocket_Functional_C_OnPersistentSubsystemPostLoad Parms{};

	Parms.Version = Version;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.OnPersistentSubsystemPreSave
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_Rocket_Functional_C::OnPersistentSubsystemPreSave()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "OnPersistentSubsystemPreSave");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.OnPersistentTranformReset
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   NewLocation                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FRotator&                  NewRotation                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor)

void ABP_Rocket_Functional_C::OnPersistentTranformReset(const struct FVector& NewLocation, const struct FRotator& NewRotation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "OnPersistentTranformReset");

	Params::BP_Rocket_Functional_C_OnPersistentTranformReset Parms{};

	Parms.NewLocation = std::move(NewLocation);
	Parms.NewRotation = std::move(NewRotation);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.OnRequestLaunch_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UVoyageRocketStateComponent*      RocketStateComponent                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::OnRequestLaunch_Event(class UVoyageRocketStateComponent* RocketStateComponent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "OnRequestLaunch_Event");

	Params::BP_Rocket_Functional_C_OnRequestLaunch_Event Parms{};

	Parms.RocketStateComponent = RocketStateComponent;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.OnRequestLaunchSequence
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UVoyageRocketStateComponent*      RocketStateComponent                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::OnRequestLaunchSequence(class UVoyageRocketStateComponent* RocketStateComponent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "OnRequestLaunchSequence");

	Params::BP_Rocket_Functional_C_OnRequestLaunchSequence Parms{};

	Parms.RocketStateComponent = RocketStateComponent;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.OnStateCompleted
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EVoyageRocketState                      State                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::OnStateCompleted(EVoyageRocketState State)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "OnStateCompleted");

	Params::BP_Rocket_Functional_C_OnStateCompleted Parms{};

	Parms.State = State;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.OnStateProgressChanged_Event
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UVoyageRocketStateComponent*      RocketStateComponent                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// EVoyageRocketState                      CurrentState                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVoyageRocketStateResult&  Result                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void ABP_Rocket_Functional_C::OnStateProgressChanged_Event(class UVoyageRocketStateComponent* RocketStateComponent, EVoyageRocketState CurrentState, const struct FVoyageRocketStateResult& Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "OnStateProgressChanged_Event");

	Params::BP_Rocket_Functional_C_OnStateProgressChanged_Event Parms{};

	Parms.RocketStateComponent = RocketStateComponent;
	Parms.CurrentState = CurrentState;
	Parms.Result = std::move(Result);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.PlayDoorLockedSound
// (BlueprintCallable, BlueprintEvent)

void ABP_Rocket_Functional_C::PlayDoorLockedSound()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "PlayDoorLockedSound");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.PlayDoorSound
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class USoundBase*                       Sound                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::PlayDoorSound(class USoundBase* Sound)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "PlayDoorSound");

	Params::BP_Rocket_Functional_C_PlayDoorSound Parms{};

	Parms.Sound = Sound;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.PlayerInteraction
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APawn*                            MyCharacter                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UInteractiveObjectComponent*      InteractiveObjectComponent                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::PlayerInteraction(class APawn* MyCharacter, class UInteractiveObjectComponent* InteractiveObjectComponent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "PlayerInteraction");

	Params::BP_Rocket_Functional_C_PlayerInteraction Parms{};

	Parms.MyCharacter = MyCharacter;
	Parms.InteractiveObjectComponent = InteractiveObjectComponent;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.PlayerInteractionRelease
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APawn*                            MyCharacter                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UInteractiveObjectComponent*      InteractiveObjectComponent                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::PlayerInteractionRelease(class APawn* MyCharacter, class UInteractiveObjectComponent* InteractiveObjectComponent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "PlayerInteractionRelease");

	Params::BP_Rocket_Functional_C_PlayerInteractionRelease Parms{};

	Parms.MyCharacter = MyCharacter;
	Parms.InteractiveObjectComponent = InteractiveObjectComponent;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.PlayFuelHatchInterruptedSound
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::PlayFuelHatchInterruptedSound(int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "PlayFuelHatchInterruptedSound");

	Params::BP_Rocket_Functional_C_PlayFuelHatchInterruptedSound Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.PlayFuelHatchSound
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class USoundBase*                       Sound                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::PlayFuelHatchSound(int32 Index_0, class USoundBase* Sound)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "PlayFuelHatchSound");

	Params::BP_Rocket_Functional_C_PlayFuelHatchSound Parms{};

	Parms.Index_0 = Index_0;
	Parms.Sound = Sound;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.QueueReward
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UVoyageScheduledActionLogic*      CustomRewardLogic                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::QueueReward(class UVoyageScheduledActionLogic* CustomRewardLogic)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "QueueReward");

	Params::BP_Rocket_Functional_C_QueueReward Parms{};

	Parms.CustomRewardLogic = CustomRewardLogic;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Rocket_Functional_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "ReceiveTick");

	Params::BP_Rocket_Functional_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.SetDoorLocation
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Vertical                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Depth                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Handle                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::SetDoorLocation(double Vertical, double Depth, double Handle)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "SetDoorLocation");

	Params::BP_Rocket_Functional_C_SetDoorLocation Parms{};

	Parms.Vertical = Vertical;
	Parms.Depth = Depth;
	Parms.Handle = Handle;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.SetDoorTimeline
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Time                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::SetDoorTimeline(double Time)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "SetDoorTimeline");

	Params::BP_Rocket_Functional_C_SetDoorTimeline Parms{};

	Parms.Time = Time;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.SetFuelHatchTime_01
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Time                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::SetFuelHatchTime_01(double Time)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "SetFuelHatchTime_01");

	Params::BP_Rocket_Functional_C_SetFuelHatchTime_01 Parms{};

	Parms.Time = Time;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.SetFuelHatchTime_02
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Time                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::SetFuelHatchTime_02(double Time)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "SetFuelHatchTime_02");

	Params::BP_Rocket_Functional_C_SetFuelHatchTime_02 Parms{};

	Parms.Time = Time;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.SetFuelHatchTime_03
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Time                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::SetFuelHatchTime_03(double Time)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "SetFuelHatchTime_03");

	Params::BP_Rocket_Functional_C_SetFuelHatchTime_03 Parms{};

	Parms.Time = Time;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.SetHatchRotation
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Alpha                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::SetHatchRotation(int32 Index_0, double Alpha)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "SetHatchRotation");

	Params::BP_Rocket_Functional_C_SetHatchRotation Parms{};

	Parms.Index_0 = Index_0;
	Parms.Alpha = Alpha;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.SetupInteractiveState
// (BlueprintCallable, BlueprintEvent)

void ABP_Rocket_Functional_C::SetupInteractiveState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "SetupInteractiveState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.ShouldIgnoreVisiblityTrace
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           InInteractor                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool ABP_Rocket_Functional_C::ShouldIgnoreVisiblityTrace(class AActor* InInteractor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "ShouldIgnoreVisiblityTrace");

	Params::BP_Rocket_Functional_C_ShouldIgnoreVisiblityTrace Parms{};

	Parms.InInteractor = InInteractor;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.TickPodSocketState
// (BlueprintCallable, BlueprintEvent)

void ABP_Rocket_Functional_C::TickPodSocketState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "TickPodSocketState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.Timeline__FinishedFunc
// (BlueprintEvent)

void ABP_Rocket_Functional_C::Timeline__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "Timeline__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.Timeline__UpdateFunc
// (BlueprintEvent)

void ABP_Rocket_Functional_C::Timeline__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "Timeline__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.TL_OpenFuelHatch_01__FinishedFunc
// (BlueprintEvent)

void ABP_Rocket_Functional_C::TL_OpenFuelHatch_01__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "TL_OpenFuelHatch_01__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.TL_OpenFuelHatch_01__UpdateFunc
// (BlueprintEvent)

void ABP_Rocket_Functional_C::TL_OpenFuelHatch_01__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "TL_OpenFuelHatch_01__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.TL_OpenFuelHatch_02__FinishedFunc
// (BlueprintEvent)

void ABP_Rocket_Functional_C::TL_OpenFuelHatch_02__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "TL_OpenFuelHatch_02__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.TL_OpenFuelHatch_02__UpdateFunc
// (BlueprintEvent)

void ABP_Rocket_Functional_C::TL_OpenFuelHatch_02__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "TL_OpenFuelHatch_02__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.TL_OpenFuelHatch_03__FinishedFunc
// (BlueprintEvent)

void ABP_Rocket_Functional_C::TL_OpenFuelHatch_03__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "TL_OpenFuelHatch_03__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.TL_OpenFuelHatch_03__UpdateFunc
// (BlueprintEvent)

void ABP_Rocket_Functional_C::TL_OpenFuelHatch_03__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "TL_OpenFuelHatch_03__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.ToggleDoor
// (BlueprintCallable, BlueprintEvent)

void ABP_Rocket_Functional_C::ToggleDoor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "ToggleDoor");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.ToggleFuelHatch_01
// (BlueprintCallable, BlueprintEvent)

void ABP_Rocket_Functional_C::ToggleFuelHatch_01()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "ToggleFuelHatch_01");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.ToggleFuelHatch_02
// (BlueprintCallable, BlueprintEvent)

void ABP_Rocket_Functional_C::ToggleFuelHatch_02()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "ToggleFuelHatch_02");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.ToggleFuelHatch_03
// (BlueprintCallable, BlueprintEvent)

void ABP_Rocket_Functional_C::ToggleFuelHatch_03()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "ToggleFuelHatch_03");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.ToggleInteractions
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// EFVoyageInteractType                    Interact_Type                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::ToggleInteractions(EFVoyageInteractType Interact_Type)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "ToggleInteractions");

	Params::BP_Rocket_Functional_C_ToggleInteractions Parms{};

	Parms.Interact_Type = Interact_Type;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.GetFuelHatchResourceType
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EModuleResourceType*                    NewParam                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::GetFuelHatchResourceType(int32 Index_0, EModuleResourceType* NewParam) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "GetFuelHatchResourceType");

	Params::BP_Rocket_Functional_C_GetFuelHatchResourceType Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);

	if (NewParam != nullptr)
		*NewParam = Parms.NewParam;
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.GetFuelModuleComponent
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UVoyageModuleComponent**          Component                                              (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::GetFuelModuleComponent(int32 Index_0, class UVoyageModuleComponent** Component) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "GetFuelModuleComponent");

	Params::BP_Rocket_Functional_C_GetFuelModuleComponent Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);

	if (Component != nullptr)
		*Component = Parms.Component;
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.GetOverrideZoneId
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class FName                             ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class FName ABP_Rocket_Functional_C::GetOverrideZoneId() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "GetOverrideZoneId");

	Params::BP_Rocket_Functional_C_GetOverrideZoneId Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.GetStateComponent
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class UVoyageRocketStateComponent**     StateComponent                                         (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Functional_C::GetStateComponent(class UVoyageRocketStateComponent** StateComponent) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "GetStateComponent");

	Params::BP_Rocket_Functional_C_GetStateComponent Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (StateComponent != nullptr)
		*StateComponent = Parms.StateComponent;
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.HasAnyChanges
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool ABP_Rocket_Functional_C::HasAnyChanges() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "HasAnyChanges");

	Params::BP_Rocket_Functional_C_HasAnyChanges Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.HasCustomData
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool ABP_Rocket_Functional_C::HasCustomData() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "HasCustomData");

	Params::BP_Rocket_Functional_C_HasCustomData Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_Rocket_Functional.BP_Rocket_Functional_C.PersistTranform
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool ABP_Rocket_Functional_C::PersistTranform() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Functional_C", "PersistTranform");

	Params::BP_Rocket_Functional_C_PersistTranform Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

