#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ReportWidget

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Voyage_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BP_ReportWidget.BP_ReportWidget_C
// 0x0028 (0x0918 - 0x08F0)
class UBP_ReportWidget_C final : public UVoyageReportWidget
{
public:
	struct FLinearColor                           SelectedButtonColor;                               // 0x08F0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UButton*                                SelectedButton;                                    // 0x0900(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           ButtonBackgroundColor;                             // 0x0908(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ReportWidget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ReportWidget_C")
	}
	static class UBP_ReportWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ReportWidget_C>();
	}
};
DUMPER7_ASSERTS_UBP_ReportWidget_C;

}

