#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Rocket_Dummy

#include "Basic.hpp"

#include "BP_Rocket_Dummy_classes.hpp"
#include "BP_Rocket_Dummy_parameters.hpp"


namespace SDK
{

// Function BP_Rocket_Dummy.BP_Rocket_Dummy_C.AnimationFinished
// (Protected, BlueprintCallable, BlueprintEvent)

void ABP_Rocket_Dummy_C::AnimationFinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Dummy_C", "AnimationFinished");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Rocket_Dummy.BP_Rocket_Dummy_C.AnimationStopped
// (Protected, BlueprintCallable, BlueprintEvent)

void ABP_Rocket_Dummy_C::AnimationStopped()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Dummy_C", "AnimationStopped");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Rocket_Dummy.BP_Rocket_Dummy_C.ExecuteUbergraph_BP_Rocket_Dummy
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Dummy_C::ExecuteUbergraph_BP_Rocket_Dummy(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Dummy_C", "ExecuteUbergraph_BP_Rocket_Dummy");

	Params::BP_Rocket_Dummy_C_ExecuteUbergraph_BP_Rocket_Dummy Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Rocket_Dummy.BP_Rocket_Dummy_C.GetFuelHatchStaticMesh
// (Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UStaticMeshComponent**            StaticMeshComponent                                    (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Dummy_C::GetFuelHatchStaticMesh(int32 Index_0, class UStaticMeshComponent** StaticMeshComponent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Dummy_C", "GetFuelHatchStaticMesh");

	Params::BP_Rocket_Dummy_C_GetFuelHatchStaticMesh Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);

	if (StaticMeshComponent != nullptr)
		*StaticMeshComponent = Parms.StaticMeshComponent;
}


// Function BP_Rocket_Dummy.BP_Rocket_Dummy_C.GetPlayerOffset
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FTransform*                      Offset                                                 (Parm, OutParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Dummy_C::GetPlayerOffset(struct FTransform* Offset)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Dummy_C", "GetPlayerOffset");

	Params::BP_Rocket_Dummy_C_GetPlayerOffset Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Offset != nullptr)
		*Offset = std::move(Parms.Offset);
}


// Function BP_Rocket_Dummy.BP_Rocket_Dummy_C.NotifyLanded
// (BlueprintCallable, BlueprintEvent)

void ABP_Rocket_Dummy_C::NotifyLanded()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Dummy_C", "NotifyLanded");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Rocket_Dummy.BP_Rocket_Dummy_C.NotifyLaunch
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  FlightDuration                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Dummy_C::NotifyLaunch(double FlightDuration)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Dummy_C", "NotifyLaunch");

	Params::BP_Rocket_Dummy_C_NotifyLaunch Parms{};

	Parms.FlightDuration = FlightDuration;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Rocket_Dummy.BP_Rocket_Dummy_C.OnAnimationFinished
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bFinished                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Dummy_C::OnAnimationFinished(bool bFinished)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Dummy_C", "OnAnimationFinished");

	Params::BP_Rocket_Dummy_C_OnAnimationFinished Parms{};

	Parms.bFinished = bFinished;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Rocket_Dummy.BP_Rocket_Dummy_C.OnHide
// (BlueprintCallable, BlueprintEvent)

void ABP_Rocket_Dummy_C::OnHide()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Dummy_C", "OnHide");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Rocket_Dummy.BP_Rocket_Dummy_C.OnReveal
// (BlueprintCallable, BlueprintEvent)

void ABP_Rocket_Dummy_C::OnReveal()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Dummy_C", "OnReveal");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Rocket_Dummy.BP_Rocket_Dummy_C.PlayLevelSequence
// (Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ULevelSequence*                   LevelSequence                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// double*                                 duration                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Dummy_C::PlayLevelSequence(class ULevelSequence* LevelSequence, double* duration)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Dummy_C", "PlayLevelSequence");

	Params::BP_Rocket_Dummy_C_PlayLevelSequence Parms{};

	Parms.LevelSequence = LevelSequence;

	UObject::ProcessEvent(Func, &Parms);

	if (duration != nullptr)
		*duration = Parms.duration;
}


// Function BP_Rocket_Dummy.BP_Rocket_Dummy_C.RemoveLevelSequence
// (Protected, BlueprintCallable, BlueprintEvent)

void ABP_Rocket_Dummy_C::RemoveLevelSequence()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Dummy_C", "RemoveLevelSequence");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Rocket_Dummy.BP_Rocket_Dummy_C.GetLevelSequence
// (Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class ULevelSequence**                  LevelSequence                                          (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_Rocket_Dummy_C::GetLevelSequence(class ULevelSequence** LevelSequence) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rocket_Dummy_C", "GetLevelSequence");

	Params::BP_Rocket_Dummy_C_GetLevelSequence Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (LevelSequence != nullptr)
		*LevelSequence = Parms.LevelSequence;
}

}

