#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SubtitleWidget

#include "Basic.hpp"

#include "Voyage_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BP_SubtitleWidget.BP_SubtitleWidget_C
// 0x0000 (0x0340 - 0x0340)
class UBP_SubtitleWidget_C final : public UVoyageSubtitleWidget
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SubtitleWidget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SubtitleWidget_C")
	}
	static class UBP_SubtitleWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_SubtitleWidget_C>();
	}
};
DUMPER7_ASSERTS_UBP_SubtitleWidget_C;

}

