#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SurvivalGuideList

#include "Basic.hpp"

#include "Voyage_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BP_SurvivalGuideList.BP_SurvivalGuideList_C
// 0x0000 (0x0610 - 0x0610)
class UBP_SurvivalGuideList_C final : public UVoyageSurvivalGuideListWidget
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SurvivalGuideList_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SurvivalGuideList_C")
	}
	static class UBP_SurvivalGuideList_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_SurvivalGuideList_C>();
	}
};
DUMPER7_ASSERTS_UBP_SurvivalGuideList_C;

}

