#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SkillViewWidget

#include "Basic.hpp"

#include "Voyage_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BP_SkillViewWidget.BP_SkillViewWidget_C
// 0x0000 (0x0630 - 0x0630)
class UBP_SkillViewWidget_C final : public UVoyageSkillViewWidget
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SkillViewWidget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SkillViewWidget_C")
	}
	static class UBP_SkillViewWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_SkillViewWidget_C>();
	}
};
DUMPER7_ASSERTS_UBP_SkillViewWidget_C;

}

