#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Switch_Toggle_ResourceSharing

#include "Basic.hpp"

#include "Voyage_structs.hpp"
#include "Voyage_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Switch_Toggle_ResourceSharing.BP_Switch_Toggle_ResourceSharing_C
// 0x0058 (0x0080 - 0x0028)
class UBP_Switch_Toggle_ResourceSharing_C final : public UVoyageModuleGenericSwitchCustomToggleFunction
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0028(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	TSet<class UVoyageModuleComponent*>           ModuleSet;                                         // 0x0030(0x0050)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, ContainsInstancedReference)

public:
	void ExecuteUbergraph_BP_Switch_Toggle_ResourceSharing(int32 EntryPoint);
	void OnToggleSwitch(class AVoyageModuleGenericSwitchActor* ThisSwitch, bool On);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Switch_Toggle_ResourceSharing_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Switch_Toggle_ResourceSharing_C")
	}
	static class UBP_Switch_Toggle_ResourceSharing_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Switch_Toggle_ResourceSharing_C>();
	}
};
DUMPER7_ASSERTS_UBP_Switch_Toggle_ResourceSharing_C;

}

