#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SaveGameDetailsWidget

#include "Basic.hpp"

#include "Voyage_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BP_SaveGameDetailsWidget.BP_SaveGameDetailsWidget_C
// 0x0058 (0x0758 - 0x0700)
class UBP_SaveGameDetailsWidget_C final : public UVoyageSaveGameDetailsWidget
{
public:
	class UThrobber*                              Throbber_114;                                      // 0x0700(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TMap<int32, class FText>                      Details;                                           // 0x0708(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SaveGameDetailsWidget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SaveGameDetailsWidget_C")
	}
	static class UBP_SaveGameDetailsWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_SaveGameDetailsWidget_C>();
	}
};
DUMPER7_ASSERTS_UBP_SaveGameDetailsWidget_C;

}

