#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_VoyageNotify_HideFromHand

#include "Basic.hpp"

#include "Voyage_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_VoyageNotify_HideFromHand.BP_VoyageNotify_HideFromHand_C
// 0x0008 (0x0040 - 0x0038)
class UBP_VoyageNotify_HideFromHand_C final : public UVoyageEquipmentReleaseFromHand
{
public:
	bool                                          Show;                                              // 0x0038(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	bool Received_Notify(class USkeletalMeshComponent* MeshComp, class UAnimSequenceBase* Animation, const struct FAnimNotifyEventReference& EventReference) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_VoyageNotify_HideFromHand_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_VoyageNotify_HideFromHand_C")
	}
	static class UBP_VoyageNotify_HideFromHand_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_VoyageNotify_HideFromHand_C>();
	}
};
DUMPER7_ASSERTS_UBP_VoyageNotify_HideFromHand_C;

}

