#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_VoyageCheat_TeleportBtn_Widget

#include "Basic.hpp"

#include "BP_VoyageCheat_TeleportBtn_Widget_classes.hpp"
#include "BP_VoyageCheat_TeleportBtn_Widget_parameters.hpp"


namespace SDK
{

// Function BP_VoyageCheat_TeleportBtn_Widget.BP_VoyageCheat_TeleportBtn_Widget_C.BndEvt__BP_TeleportLocationButton_Widget_Button_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UBP_VoyageCheat_TeleportBtn_Widget_C::BndEvt__BP_TeleportLocationButton_Widget_Button_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_VoyageCheat_TeleportBtn_Widget_C", "BndEvt__BP_TeleportLocationButton_Widget_Button_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_VoyageCheat_TeleportBtn_Widget.BP_VoyageCheat_TeleportBtn_Widget_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBP_VoyageCheat_TeleportBtn_Widget_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_VoyageCheat_TeleportBtn_Widget_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_VoyageCheat_TeleportBtn_Widget.BP_VoyageCheat_TeleportBtn_Widget_C.ExecuteUbergraph_BP_VoyageCheat_TeleportBtn_Widget
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_VoyageCheat_TeleportBtn_Widget_C::ExecuteUbergraph_BP_VoyageCheat_TeleportBtn_Widget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_VoyageCheat_TeleportBtn_Widget_C", "ExecuteUbergraph_BP_VoyageCheat_TeleportBtn_Widget");

	Params::BP_VoyageCheat_TeleportBtn_Widget_C_ExecuteUbergraph_BP_VoyageCheat_TeleportBtn_Widget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

