#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_VoyageIngameCraneHud

#include "Basic.hpp"

#include "BP_VoyageIngameCraneHud_classes.hpp"
#include "BP_VoyageIngameCraneHud_parameters.hpp"


namespace SDK
{

// Function BP_VoyageIngameCraneHud.BP_VoyageIngameCraneHud_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBP_VoyageIngameCraneHud_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_VoyageIngameCraneHud_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_VoyageIngameCraneHud.BP_VoyageIngameCraneHud_C.ExecuteUbergraph_BP_VoyageIngameCraneHud
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_VoyageIngameCraneHud_C::ExecuteUbergraph_BP_VoyageIngameCraneHud(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_VoyageIngameCraneHud_C", "ExecuteUbergraph_BP_VoyageIngameCraneHud");

	Params::BP_VoyageIngameCraneHud_C_ExecuteUbergraph_BP_VoyageIngameCraneHud Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_VoyageIngameCraneHud.BP_VoyageIngameCraneHud_C.GetModuleOfClass
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AVoyageBoatPawn*                  Parent                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UClass*                           Class_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// TSoftObjectPtr<class UObject>*          Output                                                 (Parm, OutParm, HasGetValueTypeHash)

void UBP_VoyageIngameCraneHud_C::GetModuleOfClass(class AVoyageBoatPawn* Parent, class UClass* Class_0, TSoftObjectPtr<class UObject>* Output)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_VoyageIngameCraneHud_C", "GetModuleOfClass");

	Params::BP_VoyageIngameCraneHud_C_GetModuleOfClass Parms{};

	Parms.Parent = Parent;
	Parms.Class_0 = Class_0;

	UObject::ProcessEvent(Func, &Parms);

	if (Output != nullptr)
		*Output = Parms.Output;
}


// Function BP_VoyageIngameCraneHud.BP_VoyageIngameCraneHud_C.OnPowerStateChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UVoyageModuleComponent*           SourceModule                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// bool                                    bHasPower                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_VoyageIngameCraneHud_C::OnPowerStateChanged(class UVoyageModuleComponent* SourceModule, bool bHasPower)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_VoyageIngameCraneHud_C", "OnPowerStateChanged");

	Params::BP_VoyageIngameCraneHud_C_OnPowerStateChanged Parms{};

	Parms.SourceModule = SourceModule;
	Parms.bHasPower = bHasPower;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_VoyageIngameCraneHud.BP_VoyageIngameCraneHud_C.UpdatePowerOverlay
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    HasPower                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_VoyageIngameCraneHud_C::UpdatePowerOverlay(bool HasPower)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_VoyageIngameCraneHud_C", "UpdatePowerOverlay");

	Params::BP_VoyageIngameCraneHud_C_UpdatePowerOverlay Parms{};

	Parms.HasPower = HasPower;

	UObject::ProcessEvent(Func, &Parms);
}

}

