#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_VoyagePersistentSubsystem

#include "Basic.hpp"

#include "Voyage_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_VoyagePersistentSubsystem.BP_VoyagePersistentSubsystem_C
// 0x0000 (0x0908 - 0x0908)
class UBP_VoyagePersistentSubsystem_C final : public UVoyagePersistentSubsystem
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_VoyagePersistentSubsystem_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_VoyagePersistentSubsystem_C")
	}
	static class UBP_VoyagePersistentSubsystem_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_VoyagePersistentSubsystem_C>();
	}
};
DUMPER7_ASSERTS_UBP_VoyagePersistentSubsystem_C;

}

