#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_WeatherVolumeActor

#include "Basic.hpp"

#include "BP_WeatherVolumeActor_classes.hpp"
#include "BP_WeatherVolumeActor_parameters.hpp"


namespace SDK
{

// Function BP_WeatherVolumeActor.BP_WeatherVolumeActor_C.ExecuteUbergraph_BP_WeatherVolumeActor
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_WeatherVolumeActor_C::ExecuteUbergraph_BP_WeatherVolumeActor(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_WeatherVolumeActor_C", "ExecuteUbergraph_BP_WeatherVolumeActor");

	Params::BP_WeatherVolumeActor_C_ExecuteUbergraph_BP_WeatherVolumeActor Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_WeatherVolumeActor.BP_WeatherVolumeActor_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_WeatherVolumeActor_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_WeatherVolumeActor_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

