#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CraftableObjectList

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum CraftableObjectList.CraftableObjectList
// NumValues: 0x0043
enum class ECraftableObjectList : uint8
{
	NewEnumerator7                           = 0,
	NewEnumerator0                           = 1,
	NewEnumerator2                           = 2,
	NewEnumerator8                           = 3,
	NewEnumerator1                           = 4,
	NewEnumerator9                           = 5,
	NewEnumerator3                           = 6,
	NewEnumerator10                          = 7,
	NewEnumerator4                           = 8,
	NewEnumerator11                          = 9,
	NewEnumerator5                           = 10,
	NewEnumerator12                          = 11,
	NewEnumerator6                           = 12,
	NewEnumerator14                          = 13,
	NewEnumerator15                          = 14,
	NewEnumerator16                          = 15,
	NewEnumerator17                          = 16,
	NewEnumerator19                          = 17,
	NewEnumerator21                          = 18,
	NewEnumerator44                          = 19,
	NewEnumerator22                          = 20,
	NewEnumerator23                          = 21,
	NewEnumerator24                          = 22,
	NewEnumerator25                          = 23,
	NewEnumerator26                          = 24,
	NewEnumerator27                          = 25,
	NewEnumerator28                          = 26,
	NewEnumerator30                          = 27,
	NewEnumerator31                          = 28,
	NewEnumerator32                          = 29,
	NewEnumerator33                          = 30,
	NewEnumerator34                          = 31,
	NewEnumerator43                          = 32,
	NewEnumerator36                          = 33,
	NewEnumerator37                          = 34,
	NewEnumerator38                          = 35,
	NewEnumerator39                          = 36,
	NewEnumerator40                          = 37,
	NewEnumerator41                          = 38,
	NewEnumerator50                          = 39,
	NewEnumerator42                          = 40,
	NewEnumerator51                          = 41,
	NewEnumerator52                          = 42,
	NewEnumerator53                          = 43,
	NewEnumerator54                          = 44,
	NewEnumerator55                          = 45,
	NewEnumerator56                          = 46,
	NewEnumerator57                          = 47,
	NewEnumerator58                          = 48,
	NewEnumerator59                          = 49,
	NewEnumerator60                          = 50,
	NewEnumerator61                          = 51,
	NewEnumerator62                          = 52,
	NewEnumerator63                          = 53,
	NewEnumerator64                          = 54,
	NewEnumerator67                          = 55,
	NewEnumerator68                          = 56,
	NewEnumerator69                          = 57,
	NewEnumerator70                          = 58,
	NewEnumerator71                          = 59,
	NewEnumerator72                          = 60,
	NewEnumerator73                          = 61,
	NewEnumerator74                          = 62,
	NewEnumerator75                          = 63,
	NewEnumerator76                          = 64,
	NewEnumerator77                          = 65,
	CraftableObjectList_MAX                  = 66,
};

}

