#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GameOpeningSequence

#include "Basic.hpp"


namespace SDK::Params
{

// Function GameOpeningSequence.GameOpeningSequence_DirectorBP_C.ExecuteUbergraph_GameOpeningSequence_DirectorBP
// 0x0010 (0x0010 - 0x0000)
struct GameOpeningSequence_DirectorBP_C_ExecuteUbergraph_GameOpeningSequence_DirectorBP final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_Audio_GameStart_C*                  K2Node_CustomEvent_BP_Audio_Game_Start;            // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_GameOpeningSequence_DirectorBP_C_ExecuteUbergraph_GameOpeningSequence_DirectorBP;

// Function GameOpeningSequence.GameOpeningSequence_DirectorBP_C.FadeInAudio
// 0x0008 (0x0008 - 0x0000)
struct GameOpeningSequence_DirectorBP_C_FadeInAudio final
{
public:
	class ABP_Audio_GameStart_C*                  BP_Audio_Game_Start;                               // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_GameOpeningSequence_DirectorBP_C_FadeInAudio;

}

