#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Hologram_Element_Struct

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK
{

// UserDefinedStruct Hologram_Element_Struct.Hologram_Element_Struct
// 0x0070 (0x0070 - 0x0000)
struct FHologram_Element_Struct final
{
public:
	class UStaticMesh*                            Mesh_2_59A7DA354E08F684C7D9B0B4484A21D4;           // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_8[0x8];                                        // 0x0008(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             Transform_7_7E6845EB4C595B5C8C86359E34136F2C;      // 0x0010(0x0060)(Edit, BlueprintVisible, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_FHologram_Element_Struct;

}

