#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LightBP_Factory_Ceiling_SqrLarge

#include "Basic.hpp"

#include "BP_LightBase_Rect_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass LightBP_Factory_Ceiling_SqrLarge.LightBP_Factory_Ceiling_SqrLarge_C
// 0x0000 (0x0418 - 0x0418)
class ALightBP_Factory_Ceiling_SqrLarge_C final : public ABP_LightBase_Rect_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("LightBP_Factory_Ceiling_SqrLarge_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"LightBP_Factory_Ceiling_SqrLarge_C")
	}
	static class ALightBP_Factory_Ceiling_SqrLarge_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ALightBP_Factory_Ceiling_SqrLarge_C>();
	}
};
DUMPER7_ASSERTS_ALightBP_Factory_Ceiling_SqrLarge_C;

}

