#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PDA_ContainerColors

#include "Basic.hpp"

#include "ContainerColorStruct_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PDA_ContainerColors.PDA_ContainerColors_C
// 0x0010 (0x0040 - 0x0030)
class UPDA_ContainerColors_C final : public UPrimaryDataAsset
{
public:
	TArray<struct FContainerColorStruct>          ContainerColors;                                   // 0x0030(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PDA_ContainerColors_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PDA_ContainerColors_C")
	}
	static class UPDA_ContainerColors_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPDA_ContainerColors_C>();
	}
};
DUMPER7_ASSERTS_UPDA_ContainerColors_C;

}

