#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CountdownTimer

#include "Basic.hpp"

#include "WBP_CountdownTimer_classes.hpp"
#include "WBP_CountdownTimer_parameters.hpp"


namespace SDK
{

// Function WBP_CountdownTimer.WBP_CountdownTimer_C.UpdateTime
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Time                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CountdownTimer_C::UpdateTime(double Time)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CountdownTimer_C", "UpdateTime");

	Params::WBP_CountdownTimer_C_UpdateTime Parms{};

	Parms.Time = Time;

	UObject::ProcessEvent(Func, &Parms);
}

}

