#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_VoyageIngameJetSki

#include "Basic.hpp"

#include "WBP_VoyageIngameJetSki_classes.hpp"
#include "WBP_VoyageIngameJetSki_parameters.hpp"


namespace SDK
{

// Function WBP_VoyageIngameJetSki.WBP_VoyageIngameJetSki_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_VoyageIngameJetSki_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_VoyageIngameJetSki_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_VoyageIngameJetSki.WBP_VoyageIngameJetSki_C.ExecuteUbergraph_WBP_VoyageIngameJetSki
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_VoyageIngameJetSki_C::ExecuteUbergraph_WBP_VoyageIngameJetSki(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_VoyageIngameJetSki_C", "ExecuteUbergraph_WBP_VoyageIngameJetSki");

	Params::WBP_VoyageIngameJetSki_C_ExecuteUbergraph_WBP_VoyageIngameJetSki Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_VoyageIngameJetSki.WBP_VoyageIngameJetSki_C.GetState
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    Default                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EVoyageInterfaceMode                    Mode                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   Value                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_VoyageIngameJetSki_C::GetState(bool Default, EVoyageInterfaceMode Mode, bool* Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_VoyageIngameJetSki_C", "GetState");

	Params::WBP_VoyageIngameJetSki_C_GetState Parms{};

	Parms.Default = Default;
	Parms.Mode = Mode;

	UObject::ProcessEvent(Func, &Parms);

	if (Value != nullptr)
		*Value = Parms.Value;
}


// Function WBP_VoyageIngameJetSki.WBP_VoyageIngameJetSki_C.PostInterfaceSettingsChanged
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FVoyageCustomGameUserSettings&CustomSettings                                         (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UWBP_VoyageIngameJetSki_C::PostInterfaceSettingsChanged(const struct FVoyageCustomGameUserSettings& CustomSettings)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_VoyageIngameJetSki_C", "PostInterfaceSettingsChanged");

	Params::WBP_VoyageIngameJetSki_C_PostInterfaceSettingsChanged Parms{};

	Parms.CustomSettings = std::move(CustomSettings);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_VoyageIngameJetSki.WBP_VoyageIngameJetSki_C.SetWidgetState
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bVisible                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          Target                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_VoyageIngameJetSki_C::SetWidgetState(bool bVisible, class UWidget* Target)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_VoyageIngameJetSki_C", "SetWidgetState");

	Params::WBP_VoyageIngameJetSki_C_SetWidgetState Parms{};

	Parms.bVisible = bVisible;
	Parms.Target = Target;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_VoyageIngameJetSki.WBP_VoyageIngameJetSki_C.UpdateInterfaceSettings
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVoyageCustomGameUserSettings&InSettings                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UWBP_VoyageIngameJetSki_C::UpdateInterfaceSettings(const struct FVoyageCustomGameUserSettings& InSettings)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_VoyageIngameJetSki_C", "UpdateInterfaceSettings");

	Params::WBP_VoyageIngameJetSki_C_UpdateInterfaceSettings Parms{};

	Parms.InSettings = std::move(InSettings);

	UObject::ProcessEvent(Func, &Parms);
}

}

